version: '3'

services:
    slacktoteams:
        build: .
        ports:
           - 8080:8080
        volumes:
            - ./slack2x.yaml:/app/slack2x.yaml
            - ./data:/app/data
        environment:
            - BIND_ADDR=0.0.0.0
            - BIND_PORT=8080